job continuation error handling fixes
It seems that asking for a continue of a job which has actually completed
results in the following blammo:
    JOB ERROR: 1
    Traceback (most recent call last):
      File "/usr/local/autobench/autotest/bin/job.py", line 569, in runjob
	sys.exit(1)
    SystemExit: 1

    Traceback (most recent call last):
      File "bin/autotest", line 51, in ?
	job.runjob(args[0], options.cont, options.tag, options.harness)
      File "/usr/local/autobench/autotest/bin/job.py", line 604, in runjob
	myjob.group_level = 0
    AttributeError: 'NoneType' object has no attribute 'group_level'

This seems to be caused by a couple of bugs.  The first is that we can
bail out before we have a job.  In this case we will attempt to exit(1)
to indicate completion.  This will trip an exit exception and the
surrounding try will trigger.  Here we have the following construction
which when we have a job will lead to our exiting '1':

        except Exception, e:
		[...]
		if myjob:
                        [...]
                        myjob.complete(1)

However as we have yet to instantiate myjob we will drop through to
the end of the exception handler and as its not re-raising anything we
continue on as if there was no error.  We then fall into this code
and all hell breaks loose:

        myjob.group_level = 0
        myjob.record('END GOOD', None, None)
        myjob.complete(0)

This patch sorts that out by adding explicit exits to ensure we do not drop
out.  It also makes the job completion exit much more obvious by making
a JobComplete exception object along the lines of the existing JobContinue.

Signed-off-by: Andy Whitcroft <apw@shadowen.org>