autotest-scheduller: add the dependency on mysql to the systemd service file
After a fresh install of autotest from next, I tested a new feature of arc:

$ arcli server -s
Concerns: Yes
Scheduler Running: No
Scheduler Watcher Running: Yes
Install Server Running: No
Log Disk Space Usage: 18%

Running `systemctl status autotestd` would show:

_drone_manager.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'
Traceback (most recent call last):
File "/usr/local/autotest/scheduler/autotest-scheduler", line 13, in <module>
monitor_db.main()
File "/usr/local/autotest/scheduler/monitor_db.py", line 279, in main
main_without_exception_handling()
File "/usr/local/autotest/scheduler/monitor_db.py", line 272, in main_without_exce...andling
_drone_manager.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'

Turns out that the autotestd was trying to start before the MySQL
database, which is hard dependency.

After this patch, arcli is happy about the server state:

$ arcli server -s
Concerns: No
Scheduler Running: Yes
Scheduler Watcher Running: Yes
Install Server Running: No
Log Disk Space Usage: 18%

Signed-off-by: Cleber Rosa <crosa@redhat.com>