cli/job.py: deal with parameterized_job parameter to job_create()
First appearing in commit d7249c87b56f922056917459c50df4102cb1ab68,
the 'parameterized_job' feature still is incomplete. By using a
parameterized job, one would be able to simply pass parameters to
create a job, but would lose the ability to specify a control file.

The API function 'get_info_for_clone' returns information about the
'parameterized_job' like this:

    {"error": null, "result": {
       ...
       "job" : {"parameterized_job": null, ... }
       ...
       }
    }

The job cloning functionality of 'atest', implemented in cli/job.py,
forwards this to the create_job() API function, which does NOT
accept it as a parameter. This fixes the atest cli error:

Operation create_job failed:
TypeError: create_job() got an unexpected keyword argument 'parameterized_job'

Signed-off-by: Cleber Rosa <crosa@redhat.com>