Revert "autotest_remote: Fix BUG when control files require PEP 0263 source encoding"
This reverts commit 24df2a77c97d2356840d49c11b2a05f375b51cbd.

This caused a regression on the daily regression run:

  Traceback (most recent call last):
    File "/usr/local/autotest/job.py", line 1115, in step_engine
      execfile(self.control, global_control_vars, global_control_vars)
    File "/usr/local/autotest/control.autoserv", line 1
  SyntaxError: encoding problem: with BOM (control.autoserv, line 1)

So I am reverting it

Signed-off-by: Lucas Meneghel Rodrigues <lmr@redhat.com>